version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pavel
      POSTGRES_PASSWORD: pavel
      POSTGRES_DB: postgres

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: user-files
    command: server /data --console-address :9090
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio-data:/data


volumes:
  minio-data: